export type PoolPrompt = { id: string; text: string };

export const DEFAULT_PROMPTS: PoolPrompt[] = [
  { id: "fear-unrealized", text: "What did you fear this week that never happened?" },
  { id: "control-forgotten", text: "What was within your control this week that you treated as if it weren't?" },
  { id: "complaint-vs-action", text: "What did you complain about that you could have simply fixed or accepted?" },
  { id: "approval-chased", text: "Whose approval did you chase this week, and what did it cost you?" },
  { id: "younger-self", text: "What would the person you were five years ago admire about this week?" },
  { id: "eternal-return", text: "If this week repeated forever, what habit would you change first?" },
  { id: "postponed", text: "What did you postpone this week that you know matters?" },
  { id: "anger-audit", text: "Where did anger serve you this week, and where did it use you?" },
  { id: "avoided-discomfort", text: "What discomfort did you avoid that would have made you stronger?" },
  { id: "wanted-needless", text: "What did you acquire or want this week that you could live without?" },
  { id: "patience-teacher", text: "Who tested your patience, and what did they teach you?" },
  { id: "herd-motion", text: "What did you do this week only because everyone else does it?" },
  { id: "one-year-left", text: "If you learned you had one year left, what from this week would you keep doing?" },
  { id: "small-death", text: "What small death — an ending, a loss, a change — did this week bring?" },
  { id: "busy-vs-useful", text: "Where did you mistake being busy for being useful?" },
  { id: "unsaid-truth", text: "What truth did you avoid saying this week, and to whom?" },
  { id: "grown-strength", text: "What did you handle well this week that once would have broken you?" },
  { id: "broken-promise", text: "What promise to yourself did you break, and how did you justify it?" },
  { id: "performed-virtue", text: "Where did you perform virtue instead of practicing it?" },
  { id: "obstacle-way", text: "What obstacle this week was actually the way forward?" },
  { id: "aurelius-cut", text: "What would Marcus Aurelius cut from your week without hesitation?" },
  { id: "best-hours", text: "What did you give your best hours to, and did it deserve them?" },
  { id: "peace-found", text: "When were you most at peace this week, and what were you doing?" },
  { id: "judgment-mirror", text: "What judgment about someone did you make that says more about you?" },
  { id: "luxury-necessity", text: "What luxury has quietly become a necessity for you?" },
  { id: "comfort-vs-character", text: "Where did you choose comfort over character this week?" },
  { id: "grip-loosened", text: "What are you gripping that you should hold loosely?" },
  { id: "failure-teacher", text: "What did failure teach you this week that success never could?" },
  { id: "example-to-child", text: "If this week were your example to a child, what would they learn?" },
  { id: "forgotten-in-five", text: "What will you not remember about this week in five years — and why did it consume you?" },
];
